In [2]:
#import libraries
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np
data= pd.read_csv("stud.csv")

In [3]:
data.shape

(3535, 60)

In [4]:
# in this we cant see every  column to solve this problem use
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [5]:
data.head(6)

,Drawing,Dancing,Singing,Sports,Video Game,Acting,Travelling,Gardening,Animals,Photography,Teaching,Exercise,Coding,Electricity Components,Mechanic Parts,Computer Parts,Researching,Architecture,Historic Collection,Botany,Zoology,Physics,Accounting,Economics,Sociology,Geography,Psycology,History,Science,Bussiness Education,Chemistry,Mathematics,Biology,Makeup,Designing,Content writing,Crafting,Literature,Reading,Cartooning,Debating,Asrtology,Hindi,French,English,Urdu,Other Language,Solving Puzzles,Gymnastics,Yoga,Engeeniering,Doctor,Pharmisist,Cycling,Knitting,Director,Journalism,Bussiness,Listening Music,Courses
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,BBA- Bachelor of Business Administration
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,BBA- Bachelor of Business Administration
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,BBA- Bachelor of Business Administration
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,BBA- Bachelor of Business Administration
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,BBA- Bachelor of Business Administration
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,BBA- Bachelor of Business Administration

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3535 entries, 0 to 3534
Data columns (total 60 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Drawing                 3535 non-null   int64
 1   Dancing                 3535 non-null   int64
 2   Singing                 3535 non-null   int64
 3   Sports                  3535 non-null   int64
 4   Video Game              3535 non-null   int64
 5   Acting                  3535 non-null   int64
 6   Travelling              3535 non-null   int64
 7   Gardening               3535 non-null   int64
 8   Animals                 3535 non-null   int64
 9   Photography             3535 non-null   int64
 10  Teaching                3535 non-null   int64
 11  Exercise                3535 non-null   int64
 12  Coding                  3535 non-null   int64
 13  Electricity Components  3535 non-null   int64
 14  Mechanic Parts          3535 non-null   int64
 15  Computer Parts          3535 non-null   int64
 16  Researching             3535 non-null   int64
 17  Architecture            3535 non-null   int64
 18  Historic Collection     3535 non-null   int64
 19  Botany                  3535 non-null   int64
 20  Zoology                 3535 non-null   int64
 21  Physics                 3535 non-null   int64
 22  Accounting              3535 non-null   int64
 23  Economics               3535 non-null   int64
 24  Sociology               3535 non-null   int64
 25  Geography               3535 non-null   int64
 26  Psycology               3535 non-null   int64
 27  History                 3535 non-null   int64
 28  Science                 3535 non-null   int64
 29  Bussiness Education     3535 non-null   int64
 30  Chemistry               3535 non-null   int64
 31  Mathematics             3535 non-null   int64
 32  Biology                 3535 non-null   int64
 33  Makeup                  3535 non-null   int64
 34  Designing               3535 non-null   int64
 35  Content writing         3535 non-null   int64
 36  Crafting                3535 non-null   int64
 37  Literature              3535 non-null   int64
 38  Reading                 3535 non-null   int64
 39  Cartooning              3535 non-null   int64
 40  Debating                3535 non-null   int64
 41  Asrtology               3535 non-null   int64
 42  Hindi                   3535 non-null   int64
 43  French                  3535 non-null   int64
 44  English                 3535 non-null   int64
 45  Urdu                    3535 non-null   int64
 46  Other Language          3535 non-null   int64
 47  Solving Puzzles         3535 non-null   int64
 48  Gymnastics              3535 non-null   int64
 49  Yoga                    3535 non-null   int64
 50  Engeeniering            3535 non-null   int64
 51  Doctor                  3535 non-null   int64
 52  Pharmisist              3535 non-null   int64
 53  Cycling                 3535 non-null   int64
 54  Knitting                3535 non-null   int64
 55  Director                3535 non-null   int64
 56  Journalism              3535 non-null   int64
 57  Bussiness               3535 non-null   int64
 58  Listening Music         3535 non-null   int64
 59  Courses                 3535 non-null   object
dtypes: int64(59), object(1)
memory usage: 1.6+ MB

In [7]:
data.isnull().sum()

Drawing                   0
Dancing                   0
Singing                   0
Sports                    0
Video Game                0
Acting                    0
Travelling                0
Gardening                 0
Animals                   0
Photography               0
Teaching                  0
Exercise                  0
Coding                    0
Electricity Components    0
Mechanic Parts            0
Computer Parts            0
Researching               0
Architecture              0
Historic Collection       0
Botany                    0
Zoology                   0
Physics                   0
Accounting                0
Economics                 0
Sociology                 0
Geography                 0
Psycology                 0
History                   0
Science                   0
Bussiness Education       0
Chemistry                 0
Mathematics               0
Biology                   0
Makeup                    0
Designing                 0
Content writing           0
Crafting                  0
Literature                0
Reading                   0
Cartooning                0
Debating                  0
Asrtology                 0
Hindi                     0
French                    0
English                   0
Urdu                      0
Other Language            0
Solving Puzzles           0
Gymnastics                0
Yoga                      0
Engeeniering              0
Doctor                    0
Pharmisist                0
Cycling                   0
Knitting                  0
Director                  0
Journalism                0
Bussiness                 0
Listening Music           0
Courses                   0
dtype: int64

In [8]:
#label encoding to courses
label_encoder = LabelEncoder()

# Assuming 'data' is your DataFrame and 'Courses' is a column in it
data['Courses_label'] = label_encoder.fit_transform(data['Courses'])


data['Courses_label'].value_counts()
y=data['Courses_label']

In [9]:
# categorical_column
categorical_columns = ['Drawing','Dancing','Singing','Sports','Video Game','Acting','Travelling','Gardening','Animals','Photography','Teaching','Exercise','Coding','Electricity Components','Mechanic Parts','Computer Parts','Researching','Architecture','Historic Collection','Botany','Zoology','Physics','Accounting','Economics','Sociology','Geography','Psycology','History','Science','Bussiness Education','Chemistry','Mathematics','Biology','Makeup','Designing','Content writing','Crafting','Literature','Reading','Cartooning','Debating','Asrtology','Hindi','French','English','Urdu','Other Language','Solving Puzzles','Gymnastics','Yoga','Engeeniering','Doctor','Pharmisist','Cycling','Knitting','Director','Journalism','Bussiness','Listening Music']  # Replace with your categorical columns


label_encoders = {}

for col in categorical_columns:
    label_encoder = LabelEncoder()
    data[col] = label_encoder.fit_transform(data[col])
    label_encoders[col] = label_encoder

In [10]:
data.head()

,Drawing,Dancing,Singing,Sports,Video Game,Acting,Travelling,Gardening,Animals,Photography,Teaching,Exercise,Coding,Electricity Components,Mechanic Parts,Computer Parts,Researching,Architecture,Historic Collection,Botany,Zoology,Physics,Accounting,Economics,Sociology,Geography,Psycology,History,Science,Bussiness Education,Chemistry,Mathematics,Biology,Makeup,Designing,Content writing,Crafting,Literature,Reading,Cartooning,Debating,Asrtology,Hindi,French,English,Urdu,Other Language,Solving Puzzles,Gymnastics,Yoga,Engeeniering,Doctor,Pharmisist,Cycling,Knitting,Director,Journalism,Bussiness,Listening Music,Courses,Courses_label
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,BBA- Bachelor of Business Administration,19
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,BBA- Bachelor of Business Administration,19
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,BBA- Bachelor of Business Administration,19
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,BBA- Bachelor of Business Administration,19
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,BBA- Bachelor of Business Administration,19

In [11]:
#drop the feature Course and stored data into variable dataab
dataab=data.drop(['Courses'],axis=1)# drop course column after encoding

In [12]:
dataab.head()

,Drawing,Dancing,Singing,Sports,Video Game,Acting,Travelling,Gardening,Animals,Photography,Teaching,Exercise,Coding,Electricity Components,Mechanic Parts,Computer Parts,Researching,Architecture,Historic Collection,Botany,Zoology,Physics,Accounting,Economics,Sociology,Geography,Psycology,History,Science,Bussiness Education,Chemistry,Mathematics,Biology,Makeup,Designing,Content writing,Crafting,Literature,Reading,Cartooning,Debating,Asrtology,Hindi,French,English,Urdu,Other Language,Solving Puzzles,Gymnastics,Yoga,Engeeniering,Doctor,Pharmisist,Cycling,Knitting,Director,Journalism,Bussiness,Listening Music,Courses_label
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,19
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,19
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,19
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,19
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,19

In [13]:

X=['Drawing','Dancing','Singing','Sports','Video Game','Acting','Travelling','Gardening','Animals','Photography','Teaching','Exercise','Coding','Electricity Components','Mechanic Parts','Computer Parts','Researching','Architecture','Historic Collection','Botany','Zoology','Physics','Accounting','Economics','Sociology','Geography','Psycology','History','Science','Bussiness Education','Chemistry','Mathematics','Biology','Makeup','Designing','Content writing','Crafting','Literature','Reading','Cartooning','Debating','Asrtology','Hindi','French','English','Urdu','Other Language','Solving Puzzles','Gymnastics','Yoga','Engeeniering','Doctor','Pharmisist','Cycling','Knitting','Director','Journalism','Bussiness','Listening Music']

# Create a new DataFrame 'X_df' by selecting columns from the 'dataab' DataFrame based on the 'X' list.
X_df = dataab[X]

# Create the target variable 'Y' by extracting the 'Courses_label' column from the 'dataab' DataFrame.
Y = dataab['Courses_label']

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, Y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
# Generate a classification report
# Generate a classification report to provide more detailed evaluation metrics
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)

Accuracy: 1.00
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        19
           2       1.00      0.86      0.92        21
           3       1.00      1.00      1.00        23
           4       1.00      1.00      1.00        18
           5       1.00      1.00      1.00        19
           6       1.00      1.00      1.00        25
           7       1.00      1.00      1.00        23
           8       1.00      1.00      1.00        20
           9       1.00      1.00      1.00        33
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        21
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00        23
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        19
          16       1.00      1.00      1.00        28
          17       1.00      1.00      1.00        14
          18       1.00      1.00      1.00        23
          19       1.00      1.00      1.00        20
          20       0.88      1.00      0.94        23
          21       1.00      1.00      1.00        18
          22       1.00      1.00      1.00        16
          23       1.00      1.00      1.00        25
          24       1.00      1.00      1.00        19
          25       1.00      1.00      1.00        20
          26       1.00      1.00      1.00        17
          27       1.00      1.00      1.00        20
          28       1.00      1.00      1.00        16
          29       1.00      1.00      1.00        19
          30       1.00      1.00      1.00        11
          31       1.00      1.00      1.00        18
          32       1.00      1.00      1.00        21
          33       1.00      1.00      1.00        22
          34       1.00      1.00      1.00        17

    accuracy                           1.00       707
   macro avg       1.00      1.00      1.00       707
weighted avg       1.00      1.00      1.00       707

In [15]:
import joblib

# Assuming you have a trained model object named 'model'
# Save the model to a file
joblib.dump(model , 'model .pkl')
import joblib

# Load the model from the saved file
loaded_model = joblib.load('model .pkl')

In [20]:
user_input = {}
feature_names=['Drawing','Dancing','Singing','Sports','Video Game','Acting','Travelling','Gardening','Animals','Photography','Teaching','Exercise','Coding','Electricity Components','Mechanic Parts','Computer Parts','Researching','Architecture','Historic Collection','Botany','Zoology','Physics','Accounting','Economics','Sociology','Geography','Psycology','History','Science','Bussiness Education','Chemistry','Mathematics','Biology','Makeup','Designing','Content writing','Crafting','Literature','Reading','Cartooning','Debating','Asrtology','Hindi','French','English','Urdu','Other Language','Solving Puzzles','Gymnastics','Yoga','Engeeniering','Doctor','Pharmisist','Cycling','Knitting','Director','Journalism','Bussiness','Listening Music']

# Collect user input for each feature
for feature in feature_names:
    user_value = float(input(f"Enter value for {feature} (0 or 1): "))
    user_input[feature] = user_value

# Create a DataFrame from user input
user_data = pd.DataFrame([user_input])

# Ensure that the user input DataFrame has the same columns as your training data
# Add missing columns with zeros
missing_columns = set(X_train.columns) - set(user_data.columns)
for column in missing_columns:
    user_data[column] = 0  # Add missing columns and set them to 0

# Make a prediction using the model
prediction = model.predict(user_data)

# Define a mapping from numeric values to categories
numeric_to_category = {
    0: 'Animation, Graphics and Multimedia',
    1: 'B.Arch- Bachelor of Architecture',
    2: 'B.Com- Bachelor of Commerce',
    3: 'B.Ed.',
    4: 'B.Sc- Applied Geology',
    5: 'B.Sc- Nursing',
    6: 'B.Sc. Chemistry',
    7: 'B.Sc. Mathematics',
    8: 'B.Sc.- Information Technology',
    9: 'B.Sc.- Physics',
    10: 'B.Tech.-Civil Engineering',
    11: 'B.Tech.-Computer Science and Engineering',
    12: 'B.Tech.-Electrical and Electronics Engineering',
    13: 'B.Tech.-Electronics and Communication Engineering',
    14: 'B.Tech.-Mechanical Engineering',
    15: 'BA in Economics',
    16: 'BA in English',
    17: 'BA in Hindi',
    18: 'BA in History',
    19: 'BBA- Bachelor of Business Administration',
    20: 'BBS- Bachelor of Business Studies',
    21: 'BCA- Bachelor of Computer Applications',
    22: 'BDS- Bachelor of Dental Surgery',
    23: 'BEM- Bachelor of Event Management',
    24: 'BFD- Bachelor of Fashion Designing',
    25: 'BJMC- Bachelor of Journalism and Mass Communication',
    26: 'BPharma- Bachelor of Pharmacy',
    27: 'BTTM- Bachelor of Travel and Tourism Management',
    28: 'BVA- Bachelor of Visual Arts',
    29: 'CA- Chartered Accountancy',
    30: 'CS- Company Secretary',
    31: 'Civil Services',
    32: 'Diploma in Dramatic Arts',
    33: 'Integrated Law Course- BA + LL.B',
    34: 'MBBS'
   }

# Make a prediction using the model
prediction = model.predict(user_data)

# Extract the numeric prediction (assuming prediction is a NumPy array)
numeric_prediction = prediction[0]

# Convert the numeric prediction to a categorical label
if numeric_prediction in numeric_to_category:
    categorical_prediction = numeric_to_category[numeric_prediction]


# Print the categorical prediction
print("i sugest you to go with ", categorical_prediction)

i sugest you to go with  BPharma- Bachelor of Pharmacy